-- 1. TABLA DE ÁREAS (El centro de la ubicación)
-- Aquí definimos dónde están las cosas.
create table public.areas (
  id bigint generated by default as identity primary key,
  nombre text not null unique, -- Ej: "Asesoría Jurídica"
  responsable_nombre text, -- Guardamos el nombre directo para no complicar con otra tabla si no quieres
  responsable_dni varchar(8), -- DNI validado a 8 dígitos [cite: 64]
  responsable_cargo text, -- Ej: "Jefe de Logística"
  created_at timestamp with time zone default now()
);

-- 2. TABLA CATÁLOGO SBN (Para estandarizar nombres)
-- Esto ayuda a los autocompletados del Módulo 1 
create table public.cat_denominaciones (
  id bigint generated by default as identity primary key,
  codigo_sbn varchar(8) not null unique, -- El código oficial del estado [cite: 13]
  denominacion text not null -- Ej: "COMPUTADORA PERSONAL PORTATIL"
);

-- 3. TABLA DE BIENES (El inventario real)
create table public.bienes (
  id bigint generated by default as identity primary key,
  
  -- Identificación SBN y Tramusa
  id_denominacion bigint references public.cat_denominaciones(id), -- Relación al catálogo
  codigo_patrimonial varchar(12) not null unique, -- 8 dígitos SBN + 4 Correlativo [cite: 15]
  codigo_interno varchar(4) unique, -- Código corto de 4 dígitos de la empresa [cite: 16]
  
  -- Detalles Físicos [cite: 18, 19]
  marca text,
  modelo text,
  numero_serie text, -- Debe ser único para evitar duplicados 
  color text,
  caracteristicas text, -- RAM, Procesador, etc.
  estado text check (estado in ('Nuevo', 'Bueno', 'Regular', 'Malo', 'Chatarra')), -- Validación 
  
  -- Ubicación (La clave de tu lógica)
  id_area bigint references public.areas(id) not null, -- Todo bien debe tener un área
  
  -- Auditoría
  observaciones text,
  created_at timestamp with time zone default now()
);

-- 4. TABLA DE MOVIMIENTOS (Historial / Trazabilidad) 
-- Cada vez que algo se mueva, insertamos una fila aquí.
create table public.movimientos (
  id bigint generated by default as identity primary key,
  id_bien bigint references public.bienes(id) not null,
  
  area_origen_id bigint references public.areas(id),
  area_destino_id bigint references public.areas(id),
  
  motivo text, -- Ej: "Asignación inicial", "Reparación"
  documento_referencia text, -- Ej: "Memo 001-2026"
  fecha_movimiento timestamp with time zone default now(),
  usuario_responsable text -- Quién hizo el movimiento en el sistema
);

-- INDICES SIMPLES (Para que las búsquedas vuelen)
create index idx_bienes_codigo on public.bienes(codigo_patrimonial);
create index idx_bienes_serie on public.bienes(numero_serie);
create index idx_bienes_area on public.bienes(id_area);